### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by philj56** [philj56/gbcc#11]
- [ ] Audio
  - [x] Remove global static apu struct
  - [x] Separate apu from SDL audio output
  - [ ] Make noise sound more like actual gameboy
  - [x] Time stretching audio
- [x] MBC
  - [x] MBC2
  - [x] MBC4
  - [x] Implement MBC3 RTC Registers
  - [x] Detect saving (write to SRAM)
- [x] Video
  - [x] DMG mode palette selector (see #9)
  - [x] Correct GBC colours (Completed in b6711257e1325d563330b2c35083f8831422c322)
- [x] Core
  - [x] Correct multi-cycle instruction timing
